// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"net/http"
	"user_register_service/controller"
	"user_register_service/helper"
	"user_register_service/repository"
	"user_register_service/service"
)

// Injectors from injector.go:

func InitServer() (*http.Server, func(), error) {
	userRepositoryImpl := repository.NewUserRepositoryImpl()
	db, cleanup, err := helper.NewDb()
	if err != nil {
		return nil, nil, err
	}
	userServiceImpl := service.NewUserServiceImpl(userRepositoryImpl, db)
	userControllerImpl := controller.NewUserControllerImpl(userServiceImpl)
	router := NewRouter(userControllerImpl)
	server := NewServer(router)
	return server, func() {
		cleanup()
	}, nil
}

// injector.go:

var ServerSet = wire.NewSet(helper.NewDb, repository.NewUserRepositoryImpl, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)), service.NewUserServiceImpl, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)), controller.NewUserControllerImpl, wire.Bind(new(controller.UserController), new(*controller.UserControllerImpl)), NewRouter,
	NewServer, wire.Bind(new(http.Handler), new(*httprouter.Router)),
)
